find_package(PkgConfig REQUIRED)
pkg_check_modules(ALLEGRO REQUIRED IMPORTED_TARGET allegro-5 allegro_primitives-5 allegro_image-5 allegro_font-5 allegro_ttf-5)
add_library(graphics_support graphics/window.c graphics/fractals.c graphics/demos.c)
target_link_libraries(graphics_support PUBLIC PkgConfig::ALLEGRO)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/assets")
configure_file(Exam/challenge1/skelly.png assets/skelly.png COPYONLY)
configure_file(Lab04/challenge4/coin.png assets/coin.png COPYONLY)
configure_file(Lab04/challenge5/trump_run.png assets/trump_run.png COPYONLY)
target_compile_definitions(graphics_support PRIVATE PLAYGROUND_ASSET_DIR="${CMAKE_CURRENT_BINARY_DIR}/assets")
add_executable(tetris Lab05/Solved/tetris.c)
target_link_libraries(tetris PRIVATE tetris_rules graphics_support)
add_executable(skeleton Exam/challenge1/skelly.c)
add_executable(sierpinski_triangle Lab03/Solved/challenge3/sierpinski.c)
add_executable(sierpinski_animation Lab03/Solved/challenge5/sierpinski_anim.c)
add_executable(sierpinski_carpet Exam/challenge2/sierpinski.c)
foreach(target skeleton sierpinski_triangle sierpinski_animation sierpinski_carpet)
    target_link_libraries(${target} PRIVATE graphics_support)
endforeach()
add_executable(tic_tac_toe_play PoliTicTacToe/play.c)
target_link_libraries(tic_tac_toe_play PRIVATE tic_tac_toe_rules graphics_support)
set(demo_targets hello_window primitive_art moving_shapes window_events event_logger moving_square coin_animation character_animation)
set(demo_sources Lab03/challenge1/helloworld.c Lab03/challenge2/modern.c Lab03/challenge4/anim.c
    Lab04/challenge1/close.c Lab04/challenge2/events.c Lab04/challenge3/anim.c Lab04/challenge4/sprite_anim.c Lab04/challenge5/trump.c)
foreach(index RANGE 0 7)
    list(GET demo_targets ${index} target)
    list(GET demo_sources ${index} source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE graphics_support)
endforeach()
set(graphics_targets tetris skeleton sierpinski_triangle sierpinski_animation sierpinski_carpet tic_tac_toe_play ${demo_targets})
list(APPEND playground_targets graphics_support ${graphics_targets})
if(BUILD_TESTING)
    foreach(target IN LISTS graphics_targets)
        add_test(NAME window_${target} COMMAND ${target} --smoke-test)
        set_tests_properties(window_${target} PROPERTIES TIMEOUT 20 LABELS graphics)
    endforeach()
    add_test(NAME window_tetris_ai COMMAND tetris --ai --seed 1 --smoke-test)
    set_tests_properties(window_tetris_ai PROPERTIES TIMEOUT 20 LABELS graphics)
    if(Python3_Interpreter_FOUND)
        add_test(NAME graphics_arguments COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/graphics_cli_tests.py"
                 "$<TARGET_FILE:sierpinski_triangle>" "$<TARGET_FILE:sierpinski_carpet>"
                 "$<TARGET_FILE:tetris>" "$<TARGET_FILE:skeleton>"
                 "$<TARGET_FILE:tic_tac_toe_play>" "$<TARGET_FILE:hello_window>")
    endif()
endif()
